### ISSUE TITLE
IllegalArgumentException: ClassCastException with Infinity Expansion items

### ISSUE THREAD

**Issue by mio9** [Mooy1/InfinityExpansion#100]
## Description (Required)

Illegal Argument Exception was thrown every 5 seconds 

## Steps to reproduce the Issue (Required)

- Update to minecraft 1.18.2
- Connect Infinity Expansion machines/ items to cargo network
- ClassCastException spam

## Expected behavior (Required)

Work as usual without the exception spam

## Server Log / Error Report

![image](https://user-images.githubusercontent.com/11581624/156980595-42d3c751-f676-4e1c-9537-9e465bb7fac6.png)
https://pastebin.com/rBE87r30

## Environment (Required)

 - Minecraft Version: 1.18.2
 - Slimefun Version: DEV 999
 - Plugin Version: DEV 135

![image](https://user-images.githubusercontent.com/11581624/156981214-38a372ee-83e4-438d-b4c5-b05076abdbd1.png)
![image](https://user-images.githubusercontent.com/11581624/156981281-0a82ff76-7ad7-4ca5-a18c-16a4e43906a8.png)

**Comment by mio9** [comment]
Supplimentary information: The server has crash stopped once when updating from 1.18.1 to 1.18.2 prior to the discovery of this issue

**Comment by ChitterChatter** [comment]
I am having the same issues with the same/similar issues

**Comment by mio9** [comment]
Supplementary information 2: Same type of exception was thrown when putting vanilla minecraft items on the slimefun alter, can infer that the issue was the incompatibility between slimefun and 1.18.2 more than the issue here at this addon

**Comment by Mooy1** [comment]
Fixed by 1.18.2 sf update
