### ISSUE TITLE
Option of disabling soulbound

### ISSUE THREAD

**Issue by Niko302** [Mooy1/InfinityExpansion#106]
## Description (Required)
Even when the soulbound rune is disabled in slimefun
ANCIENT_RUNE_SOULBOUND:
  enabled: false
Infinity adds lore to items that adds soulbound thus making it not possible to disable soulbound on the infinity items.

## Steps to reproduce the Issue (Required)
Craft infinity items that have the soulbound feature

## Expected behavior (Required)
Ability to disable soulbound

## Environment (Required)

 - Minecraft Version: 1.18.2
 - Slimefun Version: Slimefun DEV - 1014 (git f431aa6d)
 - InfinityExpansion vDEV - 122 (git 74e896f0)

**Comment by FN-FAL113** [comment]
As of now it adds souldbound by default to infinity gear

**Comment by Sefiraat** [comment]
I have given this a very good look-over and, for now, it’s not viable to add as optional. It’s may be possible as an enhancement to core slimefun. My best advice for now is to perhaps shift reliance away from your current soul bound solution to slimefun’s or to disable these items within IE
