### ISSUE TITLE
Infinity Machines Spit Items Out

### ISSUE THREAD

**Issue by Goonhaven** [Mooy1/InfinityExpansion#124]
## Description (Required)
For instance, the uranium extractor, advanced cobble generator, and extreme freezer all spit uranium, cobble and coolant out respectively if they are connected to a storage system which is full, instead of ceasing to work. This makes automating a nuclear reactor useless because these machines are constantly using up its power and wasting resources.

## Steps to reproduce the Issue (Required)
![2023-08-29_20 14 52](https://github.com/Mooy1/InfinityExpansion/assets/41123454/c3465d8d-ca06-433f-b9e0-4a3e6d978b98)
![2023-08-29_20 14 58](https://github.com/Mooy1/InfinityExpansion/assets/41123454/583d6342-58d9-4aaa-9387-0a2bdc457e46)

## Expected behavior (Required)
The machines should stop working when full, as do regular Slimefun machines.

## Server Log / Error Report
N/A

## Environment (Required)
 - Minecraft Version: 1.20.1
 - Slimefun Version: vDEV 1094 (git 7da1af03)
 - Plugin Version: InfinityExpansion vDEV 144 (git 9da37202)

**Comment by Sefiraat** [comment]
Hey!

Thanks for the report. This isn’t actually the machines but cargo. Cargo will naturally spit out items when moving if both the destination and origin location become filled. The behaviour can be turned off within Slimefun’s config.
