### ISSUE TITLE
dupe bug

### ISSUE THREAD

**Issue by 100petr** [Mooy1/InfinityExpansion#16]
## Description (Required)

multiplication of items through a storage unit
## Steps to reproduce the Issue (Required)

video: https://youtu.be/XwoMMhfScB4
## Expected behavior (Required)

either nothing remains in the storage unit or nothing drop out.
## Server Log / Error Report

no error, https://pastebin.com/1MCLBdzL
## Environment (Required)

 - Minecraft Version: paper 1.16.3 #220
 - CS-CoreLib Version: DEV - 91
 - Slimefun Version: DEV - 708
 - Plugin Version: DEV - 20 (version 21 does not have a storage unit, see #15)

**Comment by Mooy1** [comment]
Does this work on any item or just oak logs since the storage is made of them

**Comment by 100petr** [comment]
I tried it with obsidian and it's the same.

>
