### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by Volgeop** [Mooy1/InfinityExpansion#19]
## Description (Required)

Hi, in my Slimefun folder I see error report related to InfinityExpansion.

## Steps to reproduce the Issue (Required)

I'm sorry, but I don't know steps, but hopefully you'll know solution from error.

## Expected behavior (Required)

This error shouldn't happen.

## Server Log / Error Report

https://pastebin.com/Wmy2n638

## Environment (Required)

Server Software: Paper
  Build: git-Paper-240 (MC: 1.16.3)
  Minecraft v1.16.3-R0.1-SNAPSHOT

Slimefun Environment:
  CS-CoreLib vDEV - 91 (git e42a05d1)
  Slimefun vDEV - 729 (git 38bf2280)
  Caused by: InfinityExpansion vDEV - 28 (git 37dd7f81)

**Comment by Mooy1** [comment]
hmm did it spam this or just 1 time?

**Comment by Volgeop** [comment]
Not sure, cause I saw it just in error reports.

**Comment by Mooy1** [comment]
Ive got not idea, it works fine for me but id guess it has something to do with your via rewind as my plugin is made for 1.16

**Comment by Volgeop** [comment]
Didn't find anything in console :/  Not sure what caused it.  And I use server version 1.16.3 Paper, via rewind is only for older players
