### ISSUE TITLE
duplication

### ISSUE THREAD

**Issue by 100petr** [Mooy1/InfinityExpansion#20]
## Description (Required)

From the sf guide you can get a world breaker (and probably other items)
## Steps to reproduce the Issue (Required)

In items.yml disable INFINITY_PICKAXE
Restart server
Open sf guide -> infinity recipes -> infinity quarry 
Move INFINITY_PICKAXE to inventory
https://youtu.be/Yk-1PmKMI4s
(I did not try other items)

## Expected behavior (Required)

It will not be possible to get disabled items from the sf guide

## Server Log / Error Report

error: https://pastebin.com/QfzVfLUJ

## Environment (Required)

![image](https://user-images.githubusercontent.com/29830635/99661210-ccbd0280-2a63-11eb-8ef3-3819fd7646bf.png)

**Comment by Mooy1** [comment]
Yes since the infinity quarry requires that item you will have to disable it aswell. I will try to implement a thing that warns you.

**Comment by 100petr** [comment]
yes, I know it's needed, but it can be dragged to inventory when Is disabled. you probably understood that.

**Comment by 100petr** [comment]
and I have it disabled because players would use it more for mining than what it's for.  And you can imagine Diamond ore and fortune 40.

**Comment by Mooy1** [comment]
Its meant for mining xD

**Comment by Mooy1** [comment]
I will implement a fix next build tho
