### ISSUE TITLE
Advanced storage unit & backpack

### ISSUE THREAD

**Issue by bobhenl** [Mooy1/InfinityExpansion#21]
## Description (Required)

Hi, when player placed by accident his backpack with items to advanced storage unit, it reset his item.
## Steps to reproduce the Issue (Required)

https://streamable.com/rqlpp8
## Expected behavior (Required)

Player shouldn't loose his item / backpack shouldn't be placed there. May Slimefun can disallow placing backpacks to machines like these?

## Environment (Required)

 - Minecraft Version: 1.16.4
 - CS-CoreLib Version: 92
 - Slimefun Version: 763
 - Plugin Version: 50

**Comment by Mooy1** [comment]
Will fix in next build, also you can recover the players backpack with the command from sf.

**Comment by bobhenl** [comment]
which one? tried sf backpack player id but it was empty (all of them)
