### ISSUE TITLE
Itemducts delete items, ...

### ISSUE THREAD

**Issue by D1yt** [Mooy1/InfinityExpansion#22]
## Description (Required)

Hey, when using item-/outputducts, they have a lot of issues:
1) They sometimes delete items (and when they do, they do it all the time)
2) They only allow 1 consistent item filter
3) The blacklist doesn't work with filters
4) After a restart, the blacklist is back to whitelist again

## Steps to reproduce the Issue (Required)
After some time, or a restart, come back to your item sorter and see the issues. Even with the integrated barrels, output ducts can't insert items

## Expected behavior (Required)

The listed issues should not occur

## Server Log / Error Report

-

## Environment (Required)

 - Minecraft Version: 1.16.4
 - CS-CoreLib Version: DEV 92 (e9150d72)
 - Slimefun Version: DEV 765
 - Plugin Version: DEV 51 (fc1a547e)

**Comment by Mooy1** [comment]
ill be removing it and adding something better soonish

**Comment by D1yt** [comment]
thanks a lot

**Comment by D1yt** [comment]
Maybe you want to look into: https://github.com/BlackBeltPanda/Transport-Pipes
They use a custom resource pack and have some really cool looking pipes, which can even be hidden.
Too bad they don't support slimefun machines and don't work on 1.16.4
