### ISSUE TITLE
Hydro Generators Not Properly Connecting to Energy Network

### ISSUE THREAD

**Issue by BurningBrimstone** [Mooy1/InfinityExpansion#23]
**Description (Required)**

Hydro Generators fail to function properly. When placed on a valid energy network they will produce no energy, and upon opening their GUI simply show a  "Loading" item.

![2020-12-14_14 28 13](https://user-images.githubusercontent.com/58698520/102126124-ae56e680-3e18-11eb-8a21-888c90862041.png)

![image](https://user-images.githubusercontent.com/58698520/102126200-cc244b80-3e18-11eb-9eed-390414e6556d.png)

This also throws an error in console when restarting the server:

**Steps to reproduce the Issue (Required)**

Create a valid energy network by placing an energy regulator. Place a hydro generator.

**Expected behavior (Required)**

The Hydro Generator should properly function and produce electricity, or if the environment is not correct should display that in the GUI.

**Server Log / Error Report**

[2020-12-14-14-19.txt](https://github.com/Mooy1/InfinityExpansion/files/5691145/2020-12-14-14-19.txt)

(Only change to the file was changing it to a .txt from a .err due to GitHub incompatibility)

**Environment (Required)**

![image](https://user-images.githubusercontent.com/58698520/102126655-5e2c5400-3e19-11eb-8d53-b60a6e883071.png)
![image](https://user-images.githubusercontent.com/58698520/102126681-66848f00-3e19-11eb-9928-43538a274f69.png)

**Comment by Mooy1** [comment]
Update CS-CoreLib to v92, it seems to have an issue with auto updates 
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/#92

**Comment by BurningBrimstone** [comment]
Resolved the issue, thank you! My apologies, was not aware of the new CS-CoreLib version.
