### ISSUE TITLE
Ingots in the infinity reactor do not last as long as the sf guide says they should.

### ISSUE THREAD

**Issue by Boomer-1** [Mooy1/InfinityExpansion#25]
## Description (Required)

In the slimefun guide, it shows infinity ingots are supposed to last 24 hours when in the infinity reactor. When you put one in the reactor, it gives you a countdown starting at 72000. That only last for 12 hours. 100 in the countdown timer lasts exactly 1 minute. This should be set to 144000, not 72000, as there are 1440 minutes per day. Void ingots when put in the reactor show 12000, which is 2 hours, not 3 hours. This should be set to 18000 instead.

## Steps to reproduce the Issue (Required)

place an infinity reactor. inside place an infinity ingot and a void ingot in their respective spots and you will see they do not last as long as stated in the guide.

## Expected behavior (Required)

I expect the infinity ingot to last 24 hours as stated and the void ingot 3 hours as stated.

## Server Log / Error Report

No error logs

## Environment (Required)

 - Minecraft Version: 1.16.3
 - CS-CoreLib Version: 92
 - Slimefun Version: 768
 - Plugin Version: Infinity version 51

**Comment by Mooy1** [comment]
will fix 👍

**Comment by Boomer-1** [comment]
Thanks! Love the plugin by the way. It's going great on the yt series!
