### ISSUE TITLE
Infinity items when clicked in the infinity recipes show recipes for other items.

### ISSUE THREAD

**Issue by Boomer-1** [Mooy1/InfinityExpansion#26]
## Description (Required)

After the Dev 52 update, and all the items were re-arranged in the sf guide, I went to get the recipe for the world breaker pickaxe to test it out. I clicked on it and instead of bringing up the recipe for the world breaker, it brought up the recipe for the infinity boots. Most of the items when clicked on, show recipes for other items instead of the item you click.

## Steps to reproduce the Issue (Required)

Click on any of the recipe items in the infinity recipe tab and you will not get the recipe for that particular item.

## Expected behavior (Required)

I expected to get the correct recipe.

## Server Log / Error Report

no erros

## Environment (Required)

 - Minecraft Version:1.16.3
 - CS-CoreLib Version: Dev 92
 - Slimefun Version: Dev 769
 - Plugin Version:  Dev 52

**Comment by Mooy1** [comment]
will be fixed soon 👍
