### ISSUE TITLE
Add Exotic Garden Support

### ISSUE THREAD

**Issue by Hellcode48** [Mooy1/InfinityExpansion#27]
It would be neat if the tree grower and the farm machines would support exotic garden

**Comment by Boomer-1** [comment]
This should be entered as a suggestion on the discord, not as a bug report. This isn't a bug. Besides, there are already tree grower and crop growth accelerators for the exotic garden in the game.

**Comment by Mooy1** [comment]
^ as he said, if u want u can make suggestions in the discussion tab. Also exotic stuff is mostly useless except for the dust plants, which can be automated with advanced farmers
