### ISSUE TITLE
Storage forge not crafting and throwing error to console.

### ISSUE THREAD

**Issue by FreakyFreakyNerd** [Mooy1/InfinityExpansion#29]
## Description (Required)
The storage forge will not craft any higher tier storage units. When the items are input the barrel will eventually just disappear along with any items that were in the forge in the first place. I have tried in multiple places and checked version, and can not fin any other issue causing this.

## Steps to reproduce the Issue (Required)
Place Storage Forge In World And Putin recipe for the advanced storage unit.

## Expected behavior (Required)
The station will craft the advanced storage unit

## Server Log / Error Report
https://pastebin.com/tjiiMbxi

## Environment (Required)
Included in above pastebin

 - Minecraft Version: 1.16.4
 - CS-CoreLib Version: vDEV - 79
 - Slimefun Version: vDEV - 774
 - Plugin Version: vDEV - 55

**Comment by Mooy1** [comment]
Update CS-CoreLib to 92
