### ISSUE TITLE
Advanced Quarry is producing Cobblestone when it shouldn't

### ISSUE THREAD

**Issue by Boomer-1** [Mooy1/InfinityExpansion#30]
## Description (Required)

According to the Slimefun guide, the advanced quarry does not make cobblestone, yet it currently is, in the overworld. It is not producing cobblestone in the nether

## Steps to reproduce the Issue (Required)

Build and place an advanced quarry and let it run for a while. Cobblestone will start to show up in the overworld.

## Expected behavior (Required)

no cobblestone being produced

## Server Log / Error Report

no errors.

## Environment (Required)

 - Minecraft Version: 1.16.3
 - CS-CoreLib Version: Dev 92
 - Slimefun Version: Dev 775
 - Plugin Version:  Dev 55

**Comment by Boomer-1** [comment]
The void quarry is also producing cobblestone

**Comment by Mooy1** [comment]
Ah i forgot to show that as a output in the guide, it is meant to output cobble instead of nether items when in the overworld.
