### ISSUE TITLE
Basic Storage Units Disappearing

### ISSUE THREAD

**Issue by Boomer-1** [Mooy1/InfinityExpansion#31]
## Description (Required)

I literally just watched 3 of my basic storage units disappear into thin air. They weren't touched, they simply vanished.

## Steps to reproduce the Issue (Required)

No chance to get video recording of it as it happened randomly.

## Expected behavior (Required)

The storage units to not disappear.

## Server Log / Error Report

[2021-01-11-21-00.txt](https://github.com/Mooy1/InfinityExpansion/files/5799555/2021-01-11-21-00.txt)
[2021-01-11-21-04.txt](https://github.com/Mooy1/InfinityExpansion/files/5799558/2021-01-11-21-04.txt)
[2021-01-11-11.log.gz](https://github.com/Mooy1/InfinityExpansion/files/5799575/2021-01-11-11.log.gz)

## Environment (Required)

 - Minecraft Version: 1.16.3
 - CS-CoreLib Version: Dev 92
 - Slimefun Version: Dev 780
 - Plugin Version: Dev 57

**Comment by Mooy1** [comment]
Hmm, it seems like the storage unit had data for an amount but not the type of item stored, im adding a check for that which should prevent any more errors. Do you know what item was being stored in them?

**Comment by Boomer-1** [comment]
one was iridium, another UU matter, and the third was coal dust that gets refined once or twice. i forget the name.

**Comment by Mooy1** [comment]
Have you noticed any errors related to LiteXpansion? If it got disabled at some point or items werent registered, it would've prevented the storage unit from knowing what the stored item was.

**Comment by Boomer-1** [comment]
I was checking over the logs and was getting a lot of errors from multiple plugins, but didn't see any lite expansion ones. given how many updates came out in the last few days I"m going to restart to download all the updates, and if I get any errors related to infinity or lite expansion I'll put them here for you.

**Comment by Boomer-1** [comment]
I did get some errors after updating everything in Lite Expansion. Technically they were warnings but given the # of them and the type, they may as well have been errors. 
[latest (3).log](https://github.com/Mooy1/InfinityExpansion/files/5817906/latest.3.log)

**Comment by Mooy1** [comment]
Report the errors for each addon on their github and it shud be fixed soon

**Comment by Boomer-1** [comment]
already did. thanks
