### ISSUE TITLE
Storage Forge Only Craft's 1 Item

### ISSUE THREAD

**Issue by iLuckyx** [Mooy1/InfinityExpansion#32]
## Description (Required)
When using the storage forge to craft the advanced storage unit, no matter the amount of raw materials put in, it will only make one advanced storage unit and take all the inputted materials. For example, the advanced storage unit takes: 6x Magsteel, 2x Machine Circuits, 1x Basic storage unit to craft one. If you double, triple, etc the amount of items, it will take all the items and only give you one advanced storage unit. 

## Steps to reproduce the Issue (Required)
https://gyazo.com/a9b84faa1fa320ed4a7d882b9345b27f

## Expected behavior (Required)
I expect that if I put enough materials to craft 64 advanced storage units, I should either get 64 advanced storage units, or at least not my items taken away.

## Server Log / Error Report
There are no errors. 

## Environment (Required)
 - **Minecraft Version:** Paper Spigot (Build 409) - 1.16.4
 - **CS-CoreLib Version:** CS-CoreLib - DEV 92 (git e9150)
 - **Slimefun Version:** Slimefun4 - DEV 780 (git bc8d7)
 - **Plugin Version:**  InfinityExpansion - DEV 58 (git 099b2)
 
 Plugins used during testing:
 - CS-CoreLib - DEV 92 (git e9150)
 - Slimefun4 - DEV 780 (git bc8d7)
 - InfinityExpansion - DEV 58 (git 099b2)
 - LuckPerms (5.2.67)
 - EssentialsX 2.18.1.0

**Comment by Mooy1** [comment]
Will be fixed soon.
