### ISSUE TITLE
Storage remakes custom items

### ISSUE THREAD

**Issue by 100petr** [Mooy1/InfinityExpansion#33]
## Description (Required)

Storage remakes custom items (NBT tags disappear)
## Steps to reproduce the Issue (Required)

I use the ItemsAdder plugin
If I insert a custom item into the storage (for example fossil) it will turn into a normal iron ingot -> NBT tags disappear
Video: https://youtu.be/jle016RGCCw
## Expected behavior (Required)

NBT tags will be retained
## Server Log / Error Report

N/A
## Environment (Required)

![image](https://user-images.githubusercontent.com/29830635/104499475-742a6180-55dd-11eb-9902-67e87a812ab7.png)
![image](https://user-images.githubusercontent.com/29830635/104499487-7ab8d900-55dd-11eb-8e9a-fc89bc9ee1bb.png)

**Comment by Mooy1** [comment]
In the future custom items wont be supported, its meant to be only used for slimefun or vanilla items.
