### ISSUE TITLE
Ducts keep getting disabled 

### ISSUE THREAD

**Issue by DepressedMilkshake** [Mooy1/InfinityExpansion#34]
## Description (Required)

InfinityExpansion Item/Output ducts disabled/turned into vanilla glass after restarts.

Upon restarting the server, infinity expansion is loaded onto the server with all of its items working fine, except for The item and output ducts. Existing ducts will just be turned into normal glass, but keep their inventories & data, just unable to access them. Only way I've found around this is to keep reinstalling Infinity Expansion DEV 51, however upon restarts it auto updates to the latest (Now DEV 58) which just removes ducts from the infinity menu, and breaks the function of any previously existing ones.

## Steps to reproduce the Issue (Required)

(this is right after a restart, where storage ducts were working fine previously)
https://youtu.be/FLErOnLOgPw

## Expected behavior (Required)

Upon restart/update of the plugin the storage ducts should remain functional, instead of disappearing from the Slimefun menu and turning into pieces of orange and white glass. (Right-clicking on them like you would normally to open its white/blacklist doesn't do anything.)

## Server Log / Error Report

https://gist.github.com/DepressedMilkshake/902e092f8dc31bc896738dc04e633510
(log went over pastebin free limit)

## Environment (Required)

<img width="576" alt="2021-01-14_21 27 08" src="https://user-images.githubusercontent.com/63175510/104673827-7e696000-56b0-11eb-8424-2c7848c26a32.png">

 - Minecraft Version: 1.16.4 Java
 - CS-CoreLib Version: DEV 91
 - Slimefun Version: DEV 773
 - Plugin Version: Infinity Expansion DEV 58

**Comment by Mooy1** [comment]
They have been removed due to bugs and performance issues.

**Comment by DepressedMilkshake** [comment]
> They have been removed due to bugs and performance issues.

Is there any chance of them being added back if the issues are resolved?

**Comment by Mooy1** [comment]
Theres a chance but not the same way they were.
