### ISSUE TITLE
Unknown error in console log

### ISSUE THREAD

**Issue by Boomer-1** [Mooy1/InfinityExpansion#35]
## Description (Required)

Unsure of what the issue is. i caught this in my console about an hour ago. Because it was tied to slimefun 4 i also added the bug report there, incase the two of you need to collab on it.

## Steps to reproduce the Issue (Required)

no clue

## Expected behavior (Required)

sorry, no idea

## Server Log / Error Report

[latest.log](https://github.com/Mooy1/InfinityExpansion/files/5822498/latest.log)

## Environment (Required)

 - Minecraft Version: 1.16.3
 - CS-CoreLib Version: dev 92
 - Slimefun Version: dev 784
 - Plugin Version: Dev 58

**Comment by Mooy1** [comment]
Weird, seems like it was a random issue with saving block data to a file, although that happens thousands of times every few minutes so i'm guessing its not a big issue. The slimefun devs can probably give more info as to why it would cause the error tho.
