### ISSUE TITLE
Geo Quarry isn't interacting with the cargo management system.

### ISSUE THREAD

**Issue by Boomer-1** [Mooy1/InfinityExpansion#36]
## Description (Required)

The Geo Quarry is working perfectly as I can tell, but I cannot extract items out with the cargo management system. I have tried whitelisting and blacklisting the nodes and items, but nothing will extract out of the geo quarry.

## Steps to reproduce the Issue (Required)

place the geo quarry and attach an input node to it. Configure it to any channel and set it up to either blacklist or whitelist an item(s) to extract. 

## Expected behavior (Required)

The items to be extracted from the quarry

## Server Log / Error Report

no errors generated by console or slimefun

## Environment (Required)

 - Minecraft Version: 1.16.3
 - CS-CoreLib Version: 92
 - Slimefun Version: 789
 - Plugin Version:  61

**Comment by Mooy1** [comment]
Forgot about that, will fix

**Comment by Boomer-1** [comment]
thanks. great job on the mix of items on the quarry. very well balanced.
