### ISSUE TITLE
Clay fuel turns to heads in basic storage units when farmed from Geo Quarry

### ISSUE THREAD

**Issue by Boomer-1** [Mooy1/InfinityExpansion#38]
## Description (Required)

I am having cargo pull Clay Fuel from the Geo Miner. When it reaches the cargo advanced output node attached to the basic storage unit, it is still Clay Fuel. When it makes the left slot of the basic storage unit, it is still clay fuel. From there, going to the right it turns into player heads. 

## Steps to reproduce the Issue (Required)

https://youtu.be/BvRBkD9G2BY

## Expected behavior (Required)

Clay fuel to stay as clay fuel

## Server Log / Error Report

no slimefun errors or server errors generated

## Environment (Required)

 - Minecraft Version: 1.16.3
 - CS-CoreLib Version: 92
 - Slimefun Version: 789
 - Plugin Version:  63

**Comment by Mooy1** [comment]
I'm guessing its due to Claytech's low quality code and item system not working to well with Slimefun, but i'll look into it.

**Comment by Boomer-1** [comment]
I will have to test it out. I abandoned going to other planets in Claytech due to all the problems I saw in the code and I know zero about java code.

**Comment by Boomer-1** [comment]
i tested it and the heads do not craft the fuel.
