### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bobhenl** [Mooy1/InfinityExpansion#40]
## Description (Required)

Hi, I have some error in console.
## Steps to reproduce the Issue (Required)

Sorry, but I don't know, but hopefully you could read it from error report.
## Expected behavior (Required)

Any errors.
## Server Log / Error Report

https://pastebin.com/9KsvETGR
## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: any
 - Slimefun Version: 806
 - Plugin Version: 66

**Comment by Mooy1** [comment]
will be fixed in next build
