### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ArrozElManko** [Mooy1/InfinityExpansion#41]
## Description (Required)
Error console

## Expected behavior (Required)
any

## Server Log / Error Report
https://pastebin.com/

## Environment (Required)
 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: any
 - Slimefun Version:  810
 - Plugin Version:  66

**Comment by Mooy1** [comment]
pastebin is empty

**Comment by ArrozElManko** [comment]
ups sorry https://pastebin.com/ZQ8KZTZE

**Comment by Mooy1** [comment]
I need the stacktrace, itll take up alot of lines.
