### ISSUE TITLE
Dust Fabricator disappear bug

### ISSUE THREAD

**Issue by waleks647** [Mooy1/InfinityExpansion#42]
## Description (Required)
The Dust Fabricator doesn't work and deletes itself from the world

## Steps to reproduce the Issue (Required)
Place the Dust Fabricator and right click it to open it's GUI, then it's status goes into loading and shortly after it just disappears from the world. 

## Expected behavior (Required)
For the Dust Fabricator to work correctly and expect power and materials

## Server Log / Error Report
https://pastebin.com/FGS4NJ4M

## Environment (Required)
![sfversions](https://user-images.githubusercontent.com/78630612/107107795-adc34680-67f0-11eb-82c6-a0816756b262.png)

**Comment by Mooy1** [comment]
fixed in 70
