### ISSUE TITLE
Cannot put (filled) flasks of knowledge into a barrel

### ISSUE THREAD

**Issue by southernwindle** [Mooy1/InfinityExpansion#43]
## Description (Required)

When placing (filled) flasks of knowledge in any barrel type, the barrel fails to accept them. All other tested items have worked perfectly inside of the barrels however I can not seem to put any flasks of knowledge in.
This is an issue seeing as the experience collector outputs filled flasks of knowledge (the ones with just a green title and no lore) and there isn't a way to store them in a barrel.

## Steps to reproduce the Issue (Required)

Obtain a flask of knowledge
Fill it with experience to get the other type of Flask of Knowledge (one that comes from XP collector)
Place a barrel
Put the flask of knowledge in the barrel

## Expected behavior (Required)

The barrel would accept the flask of knowledge and put it in the other slot

## Server Log / Error Report

https://pastebin.com/Qvud6car

## Environment (Required)

Paper 138
Slimefun 792
InfinityExpansion 71 (tested on 72 aswell)
SFCalc 15
LiteXpansion 124
ExtraHeads 21
SlimyTreeTaps 17
ExtraGear 12
CMI 8.7.8.0
ExoticGarden 71

 - Minecraft Version: 1.16.1
 - CS-CoreLib Version: None
 - Slimefun Version: 792
 - Plugin Version: 71 (tested on 72 aswell)

**Comment by Mooy1** [comment]
Ya, currently storage units can only support the 'default' version of any slimefun/vanilla item. So no renamed, enchanted, or nbt data changes.
