### ISSUE TITLE
All quarries are only outputting cobblestone, and that's all that shows in the guide.

### ISSUE THREAD

**Issue by Boomer-1** [Mooy1/InfinityExpansion#45]
## Description (Required)

Right now, all the quarries of infinity expansion are just producing cobblestone. It started about an hour ago, slowly items started disappearing from the guide and what it produced. If you look in the guide, that's also all that's in there, just cobblestone.

## Steps to reproduce the Issue (Required)

craft a quarry, place it, power it, just cobble gets made.

## Expected behavior (Required)

all the normal items to be produced.

## Server Log / Error Report

no errors in logs

## Environment (Required)

 - Minecraft Version: 1.16.3
 - CS-CoreLib Version: not installed
 - Slimefun Version: Dev 819
 - Plugin Version: Dev 78

**Comment by Mooy1** [comment]
sent out fix 👍
