### ISSUE TITLE
Advanced disenchanter isn't working

### ISSUE THREAD

**Issue by Boomer-1** [Mooy1/InfinityExpansion#46]
## Description (Required)

When trying to use the Advanced disenchanter, by placing a vanilla book and an enchanted tool in the disenchanter, and having it powered, it didn't do anything.

## Steps to reproduce the Issue (Required)

https://youtu.be/8hgNsdWLQHs

## Expected behavior (Required)

The disenchanter to remove the enchantment

## Server Log / Error Report

no errors

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: removed
 - Slimefun Version: Dev 833
 - Plugin Version: Dev 92

**Comment by Mooy1** [comment]
next build should fix 👍
