### ISSUE TITLE
the things of this addon has disappeared in my slimefun GUI

### ISSUE THREAD

**Issue by YYYork** [Mooy1/InfinityExpansion#48]
- Minecraft Version:paperspigot 1.16.4
 - CS-CoreLib Version:CS-CoreLib vDEV - 92 (git e9150d72)
 - Slimefun Version:v4.9-stable-210220
 - Plugin Version: InfinityExpansion - DEV 93 (git 69b78).jar
 - 
as pictures
![image](https://user-images.githubusercontent.com/80703116/111182277-b9710c80-85e9-11eb-8f87-be88648f345b.png)
![image](https://user-images.githubusercontent.com/80703116/111182348-cb52af80-85e9-11eb-8b24-4873227575a0.png)
![image](https://user-images.githubusercontent.com/80703116/111182367-cf7ecd00-85e9-11eb-852e-146563dbc840.png)

so what happened?
the log has been reported at https://pastebin.com/SXFzvifG

**Comment by Mooy1** [comment]
Update slimefun to latest dev
