### ISSUE TITLE
Ancient Debris Dupe with Smelter's Pickaxe + Vein Miner Rune

### ISSUE THREAD

**Issue by FauzanAlfansa** [Mooy1/InfinityExpansion#49]
## Description (Required)
If you equip Smelter's Pickaxe with Vein Mine Rune and break Ancient Debris while crouching, it will drop both ancient debris and nether scrap.

## Steps to reproduce the Issue (Required)
https://www.youtube.com/watch?v=JdCG2ZIqiNY

## Expected behavior (Required)
It should drop only nether scraps

## Environment (Required)
 - Minecraft Version: Paper 1.16.5
 - CS-CoreLib Version: DEV-92
 - Slimefun Version: DEV-842
 - Plugin Version: DEV-93

**Comment by Mooy1** [comment]
fixed in next build
