### ISSUE TITLE
Stoneworks Factory can be used as vanilla blast furnace with hoppers

### ISSUE THREAD

**Issue by andris155** [Mooy1/InfinityExpansion#53]
## Description (Required)

Stoneworks Factory can be used as vanilla blast furnace with hoppers.

## Steps to reproduce the Issue (Required)

1. Build this simple furnace system from hopper and chests.

![2021-03-28_14 07 18](https://user-images.githubusercontent.com/8324198/112751622-42ffe180-8fcf-11eb-9579-1aa75e7dd8ec.png)

2. Place gold ore towards the chest.
3. Place coal next to the furnace chest.
4. Open the chest under the furnace.

<img width="259" alt="95680620-40edc600-0bdb-11eb-8690-3039911c3cbc" src="https://user-images.githubusercontent.com/8324198/112751670-7478ad00-8fcf-11eb-82b0-550c1de63a7b.png">

## Expected behavior (Required)

Stoneworks Factory can't used as vanilla blast furnace with hoppers.

## Server Log / Error Report

None

## Environment (Required)

Tuinity git-Tuinity-"c303521" (MC: 1.16.5)
Slimefun DEV - 861 (git 73b5ef8b)
Metrics-Module #21
Java 11

Installed Addons: (3)
  InfinityExpansion vDEV - 98 (git 4cf7e322)
  FoxyMachines vDEV - 42 (git ae8d8aba)
  DynaTech vDEV - 88 (git c06f0e25)

**Comment by Mooy1** [comment]
will be fixed in 101
