### ISSUE TITLE
Singularity false recipe

### ISSUE THREAD

**Issue by Sanszi** [Mooy1/InfinityExpansion#54]
The slimefun guide shows that the player needs 9*64 ingots to craft a singularity (any type), but in reality it takes either 4000 or 6000 ingots to craft a single piece. Would it be possible to indicate these numbers in the recipes, instead of falsely the nine stacks?

**Comment by Mooy1** [comment]
Not possible since the guide only shows the first 9 stacks. However, if you use sfcalc it will say the correct amount.
