### ISSUE TITLE
An Exception was caught while ticking a Cargo network

### ISSUE THREAD

**Issue by andris155** [Mooy1/InfinityExpansion#55]
## Description (Required)

This ItemStack has no ItemMeta! Make sure to check ItemStack#hasItemMeta() before accessing this method!

## Steps to reproduce the Issue (Required)

1. Console error when uses the Strainer Base.

## Expected behavior (Required)

No console error when uses the Strainer Base.

## Server Log / Error Report

https://pastebin.com/qkqBdnDM

## Environment (Required)

[12:35:34 INFO]: This Server uses the following setup of Slimefun:
Tuinity git-Tuinity-"d5261ad" (MC: 1.16.5)
Slimefun DEV - 878 (git 485dec74)
Metrics-Module #21
Java 11

Installed Addons: (14)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  PomaExpansion v1.3.1
  SlimefunFix v3.0
  FoxyMachines vDEV - 44 (git d2d14cd8)
  EcoPower vDEV - 3 (git 18ba903d)
  DynaTech vDEV - 97 (git e62bcb6b)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  InfinityExpansion vDEV - 100 (git 65892de0)
  RestrictedCreative v2.4.8
  SFCalc vDEV - 20 (git 29ba88c6)
  LiteXpansion vDEV - 145 (git 4c36f4f9)
  FluffyMachines vDEV - 75 (git 10ca2094)

**Comment by Mooy1** [comment]
will be fixed in build 102 👍

**Comment by andris155** [comment]
The build 102 not released. The build 101 not fixed this.

**Comment by Mooy1** [comment]
Ye, the fix is in 102 but i dont wanna release a whole build for 1 small rare thing, so it will be a bit while i fix other stuff
