### ISSUE TITLE
TranscEndence daxi and InfinityX armor bug

### ISSUE THREAD

**Issue by SimpRain** [Mooy1/InfinityExpansion#56]
Infinity armor overwrites and deletes daxi buff.
Tried it 3 times using daxi r (regen buff)

Situation1  wearing full infiX armor and using daxi r resulted in not getting the buff

Situation2 using the daxi r before wearing infiX armor resulted in the regen buff getting overwritten by infiX and removing infiX armor did not get the buff back

Situation3 using daxi r and putting on infiX armor EXCEPT the pants which had regen resulted in keeping the buff

From what I think, the buffs get overwritten by infiX armor and thus causing the problem

**Comment by Mooy1** [comment]
I would recomend reporting this to Transendence and telling him to re apply the affect each minute or smth, because I'm just using Slimefuns method of apply potion effects with armor.

**Comment by Mooy1** [comment]
I think it would be best to make an issue on slimefun, and hopefully someone will make it so it won't override higher level effects.
