### ISSUE TITLE
Advanced Anvil use-enchant-level-limit and enchant-level-limit settings is missing

### ISSUE THREAD

**Issue by andris155** [Mooy1/InfinityExpansion#57]
## Description (Required)

The Slimefun added to disanchanters and enchanters the use-enchant-level-limit and enchant-level-limit settings.
This settings is missing from Advanced Anvil. So you can easily breaks the enchanters and disenchanters limit with Advanced Anvil.

## Steps to reproduce the Issue (Required)

1. Use advanced anvil for an enchanting that goes beyond the enchanter and disenchanter limit.

## Expected behavior (Required)

The enchant-level-limit and enchant-level-limit settings available for Advanced Anvil.

## Environment (Required)

Tuinity git-Tuinity-"7d36676" (MC: 1.16.5)
Slimefun DEV - 879 (git f3765ba7)
Metrics-Module #21
Java 11

Installed Addons: (19)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  PomaExpansion v1.3.1
  FoxyMachines vDEV - 44 (git d2d14cd8)
  EcoPower vDEV - 4 (git 2a08d31d)
  HotbarPets vDEV - 37 (git 63b1553e)
  DynaTech vDEV - 102 (git 378f136c)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  InfinityExpansion vDEV - 101 (git bf00280c)
  RestrictedCreative v2.4.8
  SFCalc vDEV - 20 (git 29ba88c6)
  LiteXpansion vDEV - 145 (git 4c36f4f9)
  SimpleUtils vDEV - 5 (git 8d51c591)
  SlimyTreeTaps vDEV - 18 (git ab11a282)
  MobCapturer vDEV - 15 (git a42c9e0c)
  TranscEndence vDEV - 32 (git 06e323c6)
  FluffyMachines vDEV - 77 (git c50768fa)
  GeneticChickengineering vDEV - 13 (git 37cffcbb)

**Comment by Mooy1** [comment]
You set the limits in the config...

**Comment by andris155** [comment]
The config settings do nothing.

**Comment by andris155** [comment]
It is set to level 9 yet but Advanced Anvil places the level 10 enchant to the sword.

**Comment by andris155** [comment]
@Mooy1 InfinityExpansion limit only for combine 2 item. The Slimefun limit is limit the max enchants level is supported.
Currently the Advanced Anvil placed high 10+ level enchants from one item to another.
![Screenshot 2021-04-17 194309](https://user-images.githubusercontent.com/8324198/115121864-40cce980-9fb5-11eb-8b8e-d06ae095125c.jpg)
![Screenshot 2021-04-17 194327](https://user-images.githubusercontent.com/8324198/115121867-432f4380-9fb5-11eb-9f24-e5c63d9e15e1.jpg)
![Screenshot 2021-04-17 194347](https://user-images.githubusercontent.com/8324198/115121868-44607080-9fb5-11eb-9734-87a5963f1adc.jpg)

**Comment by Mooy1** [comment]
Ya, you cant get a smite 20 without setting the limit to atleast 20.
