### ISSUE TITLE
Strainer base performance is not good

### ISSUE THREAD

**Issue by andris155** [Mooy1/InfinityExpansion#58]
## Description (Required)

The Strainer base sometimes uses lot of server CPU.

![2021-04-19_16 07 46](https://user-images.githubusercontent.com/8324198/115252447-c4a8e200-a12b-11eb-9469-c2f9eaee3577.png)

## Steps to reproduce the Issue (Required)

1. Uses Strainer bases.

## Expected behavior (Required)

The Strainer base no uses lot of server CPU.

## Server Log / Error Report

Sf timings: https://pastebin.com/HssZ5Lzd
Spark: https://spark.lucko.me/tXqPqrdwbj
Timings: https://timings.aikar.co/?id=955967a59838457ca69daa48b295f628

## Environment (Required)

[15:58:42 INFO]: This Server uses the following setup of Slimefun:
Tuinity git-Tuinity-"7d36676" (MC: 1.16.5)
Slimefun DEV - 879 (git f3765ba7)
Metrics-Module #21
Java 11

Installed Addons: (14)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  PomaExpansion v1.3.1
  SlimefunFix v3.0
  FoxyMachines vDEV - 44 (git d2d14cd8)
  EcoPower vDEV - 4 (git 2a08d31d)
  DynaTech vDEV - 102 (git 378f136c)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  InfinityExpansion vDEV - 102 (git f08c00e6)
  RestrictedCreative v2.4.8
  SFCalc vDEV - 20 (git 29ba88c6)
  LiteXpansion vDEV - 145 (git 4c36f4f9)
  FluffyMachines vDEV - 77 (git c50768fa)

**Comment by Mooy1** [comment]
Players shouldn't be making 500+ of them, they are meant to be super early game before you get a dust farm, so id let them know that they aren't efficient at all. I will try to reduce the timings of them but it is a similar issue to hydro generators.

**Comment by andris155** [comment]
This not fixable? :(

**Comment by Mooy1** [comment]
Ill still try to further reduce the timings
