### ISSUE TITLE
Infinite Loading with (Certain?) Machines

### ISSUE THREAD

**Issue by razorrider7** [Mooy1/InfinityExpansion#59]
## Description (Required)

Machines placed by players say "Loading" in their GUI forever. We have tested both the Strainer Base and the Basic Solar Panel. You are unable to use them because they don't run, or don't produce energy.
## Steps to reproduce the Issue (Required)

Place a Strainer Base or Basic Solar Panel, or possibly other machines.
Right-click machine to open GUI:
https://rz7.xyz/RuRu8/HUJICIxI11.png
https://rz7.xyz/RuRu8/VInoYaJa85.png
## Expected behavior (Required)

I expected the solar panel and the Strainer Base to start working when placed.
## Server Log / Error Report

https://pastebin.com/AnsTwaPQ
## Environment (Required)

Tuinity git-Tuinity-"32b4d52" (MC: 1.16.5)
Slimefun DEV - 880 (git dc3b5bb7)
Metrics-Module #21
Java 11
Installed Addons: (6)
ClayTech v1.2.21
InfinityExpansion vDEV - 103 (git 765f00a7)
ExtraTools vDEV - 26 (git 0cb2ad70)
IllegalStack v2.2.2a
CMI v8.8.2.6
FluffyMachines vDEV - 78 (git e93c66b1)

**Comment by Mooy1** [comment]
Do you have ticking enabled for them and are they enabled in the world?

**Comment by razorrider7** [comment]
I haven't disabled them in the world, at least, and how would I check if ticking is enabled for them?

**Comment by razorrider7** [comment]
Just from Infinity so far. These machines do not work (possibly more):

- Basic Solar Panel
- Basic Virtual Farm
- Basic Tree Grower
- Hydro Generator
- Strainer Base
- Advanced Tree Grower

**Comment by Mooy1** [comment]
Would you mind sending a copy of your server files/plugins folder so i can try to reproduce it?

**Comment by Mooy1** [comment]
I think its fixed in latest dev, im closing this cause i can't repoduce it.
