### ISSUE TITLE
Resource Synthesizer cause -2M J but the block lore says 1M J / use

### ISSUE THREAD

**Issue by andris155** [Mooy1/InfinityExpansion#60]
## Description (Required)

Resource Synthesizer cause -2M J but the block lore says 1M J / use.

## Steps to reproduce the Issue (Required)

1. Place down the Energy regulator and the Resource Synthesizer.

![2021-04-21_15 45 28](https://user-images.githubusercontent.com/8324198/115564894-319db280-a2b9-11eb-84ba-3e5991ccc366.png)
![Screenshot 2021-04-21 154817](https://user-images.githubusercontent.com/8324198/115564915-35313980-a2b9-11eb-89bb-9bdba4e86503.jpg)

## Expected behavior (Required)

Resource Synthesizer cause -1M J?

## Environment (Required)

Tuinity git-Tuinity-"7d36676" (MC: 1.16.5)
Slimefun DEV - 881 (git dcc5648c)
Metrics-Module #21
Java 11

Installed Addons: (19)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  PomaExpansion v1.3.1
  FoxyMachines vDEV - 44 (git d2d14cd8)
  EcoPower vDEV - 4 (git 2a08d31d)
  HotbarPets vDEV - 37 (git 63b1553e)
  DynaTech vDEV - 102 (git 378f136c)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  InfinityExpansion vDEV - 103 (git 765f00a7)
  RestrictedCreative v2.4.8
  SFCalc vDEV - 20 (git 29ba88c6)
  LiteXpansion vDEV - 146 (git 0064ae01)
  SimpleUtils vDEV - 5 (git 8d51c591)
  SlimyTreeTaps vDEV - 18 (git ab11a282)
  MobCapturer vDEV - 15 (git a42c9e0c)
  TranscEndence vDEV - 33 (git e9b4de1a)
  FluffyMachines vDEV - 79 (git 15a0fad9)
  GeneticChickengineering vDEV - 13 (git 37cffcbb)

**Comment by Mooy1** [comment]
thats cuz it can hold 2 mil at a time but will only use 1 mil.
