### ISSUE TITLE
Gold dusts "Duplication" with infinity ingot former + ore grinder

### ISSUE THREAD

**Issue by Overseer9** [Mooy1/InfinityExpansion#63]
## Description (Required)
idk if it was intended or not
with 1 infinity ingot former and 16 ore grinders, 32 gold dust duped for each 2 slimefun ticks(8kJ total energy used on each cycle)

## Steps to reproduce the Issue (Required)
- place infinity ingot former and ore grinders
- setup cargo and energy for the machines (infinity ingot former -> ore grinders -> storage-> infinity ingot former -> ...)
- put 64 gold dusts inside infinity ingot former
- wait and check the storage, the gold dusts starts duplicating

## Expected behavior (Required)
I'd expect the infinity ingot former only produce 10x 24c gold ingots or less so it won't have any surplus on grinding it back into dusts

## Server Log / Error Report
No error report

## Environment (Required)
![image](https://user-images.githubusercontent.com/81430883/117672981-efdb9a00-b1dc-11eb-8cd8-edd72d2398c4.png)

![image](https://user-images.githubusercontent.com/81430883/117673064-041f9700-b1dd-11eb-9691-731ba2454864.png)

**Comment by Mooy1** [comment]
Fixed in latest
