### ISSUE TITLE
Infinity barrel storage signs

### ISSUE THREAD

**Issue by GalaxyKat11** [Mooy1/InfinityExpansion#65]
I noticed just before logging off last night that signs placed on infinity barrels (that show stored quantities) are not displaying correctly for blocks of Redstone and blocks of Lapis Lazuli. They both display "Block of 1".
The ones I have set up for coal,  coal blocks,  dusts, xp and netherite ingots all work as expected.
I cannot provide versions the server is running for a few hours when I can log back on.

**Comment by Mooy1** [comment]
Its because the name is too long for the sign, ill see what i can do to fix it

**Comment by GalaxyKat11** [comment]
Actually, Lapis Lazuli Block is now showing correctly but Redstone Block (which is shorter in length) is showing "Block of 1"
![Screenshot (82)](https://user-images.githubusercontent.com/65092397/119419088-74dbae80-bcc7-11eb-907e-1b8e29229a1c.png)

**Comment by Boomer-1** [comment]
because it won't fit on the sign.

**Comment by Mooy1** [comment]
Fixed in build 118, it now has 2 lines of space and will group words 'smartly'
