### ISSUE TITLE
error enabling plugin

### ISSUE THREAD

**Issue by istarengwa** [Mooy1/InfinityExpansion#66]
## Description (Required)
Recently, a huge error message arrives when starting the server, and the addon does not work, players can grab the nether star in the sf guide, but do not have access to infinite recipes

## Server Log / Error Report
https://pastebin.com/dhSX58az

## Environment (Required)
 - Minecraft Version:  purpurclip-1131 (Paper 1.16.5)
 - Slimefun Version: latest (Dev 913)
 - Plugin Version: latest (Dev 111)

**Comment by Mooy1** [comment]
Are you sure your Slimefun Version is actually dev 913? not RC or an unofficial modified version?

**Comment by istarengwa** [comment]
I use this link 

https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/

**Comment by Mooy1** [comment]
Make sure you have no other Slimefun.jars first. Also try deleting Slimefun and Infinity and downloading the latest jars just in case.

**Comment by istarengwa** [comment]
it's already done, several times, I even created a new server with all the plugins of the current server + the new sf and infinity jar, same problem. 

Do not close the ticket, I am currently doing a lot of tests on the test server to find out if your addon is incompatible with one of the plugins I have, if I find it I will warn you.

**Comment by istarengwa** [comment]
Hello, the problem came from "CS-CoreLib - DEV 92 (git e9150)" once deactivated, no more problem
