### ISSUE TITLE
Storage Unit Signs not dropping

### ISSUE THREAD

**Issue by AN0NISN4P** [Mooy1/InfinityExpansion#71]
## Description (Required)
When a sign is placed directly onto a Storage Unit, if the Storage Unit is empty, and then broken by a player, the Sign on the unit will not drop. If the Sign however is placed on a different supporting block, and that block is broken, the Sign drops like normal

## Steps to reproduce the Issue (Required)
1. Place a Storage Unit
2. Place a sign on it (Top or Side)
3. Break Storage Unit

The left 2 boxes on the image below have the sign directly placed on them. The right 2 boxes have the sign placed on a Glass Pane.
![2021-08-13_12 52 13](https://user-images.githubusercontent.com/42655737/129347592-fd61998f-5d30-48fd-b2a1-f2b05c4abfcf.png)
_Setup for testing Direct Sign placement vs Indirect Sign placement_

## Expected behavior (Required)
For each of the 4 Storage Units shown in the image above, the sign is expected to drop, once the supporting block (Storage Unit / Glass Pane) is broken. The Empty Storage Unit, with the Sign directly on it does not follow the expected behavior

## Environment (Required)

 - Minecraft Version: 1.17.1
 - Slimefun Version: DEV - 960
![Gyazo_SlimefunVersion](https://gyazo.com/7d84bae3e3e33aed51c0177876fa7fea)
 - Plugin Version: DEV - 119
![Gyazo_InfinityExpansionVersion](https://gyazo.com/206d120075deba286aff5f5bf640ee07)

**Comment by Mooy1** [comment]
Will be fixed in the next build 👍
