### ISSUE TITLE
Reinforced Storage bug

### ISSUE THREAD

**Issue by Manu2270** [Mooy1/InfinityExpansion#72]
## Description 
Sometimes the reinforced storage stops storing items and on breaking it drops a basic storage system and items are lost 

## Steps to reproduce the Issue 

https://user-images.githubusercontent.com/89065340/129681097-06beb501-7805-4c3b-b8e9-23fa765aa374.mp4

When freshly loaded the chunks this bug occurs, it happened three time to me. And each time i break it , it drops a empty basic storage

## Expected behavior 
  The storage should drop a reinforced storage system on breaking containing items which were stored in it. 

## Environment (Required)

 - Minecraft Version:
 - Slimefun Version:
 - Plugin Version: 
![unknown-47](https://user-images.githubusercontent.com/89065340/129681537-89c3a2b5-016d-4f09-828a-9c31efbbaee4.png)

**Comment by Mooy1** [comment]
This is do too the unstableness of Slimefun's BlockStorage system, there isn't much i can do about it unfortunately
