### ISSUE TITLE
Smelter Pickaxe not dropping other items

### ISSUE THREAD

**Issue by ItchyDitchy** [Mooy1/InfinityExpansion#73]
## Description (Required)
A Vein miner Rune added to a Smelter Pickaxe and triggering it will not drop any items from broken blocks, like diorite and etc. Version is 1.17.1. Using Tuinity as server jar. Also according to the code, it doesn't drop if is a smelter pick and only drop if item is smeltable. Fortune doesn't work while using the rune and the pickaxe, the pickaxe just nerfs it quite a bit.

## Steps to reproduce the Issue (Required)
Add a vein miner rune to a smelter pickaxe -> break a block while using the vein mine or shifting -> The block won't drop if it isn't smeltable.

## Expected behavior (Required)
For it to still drop blocks.

## Server Log / Error Report
No errors as this is just a missing feature or missing support.

## Environment (Required)

 - Minecraft Version: 1.17.1 Tuinity
 - Slimefun Version: DEV - 961 (git e187d878)
 - Plugin Version: DEV - 119 (git 80aecf33)

**Comment by Mooy1** [comment]
Should be fixed in next build
