### ISSUE TITLE
dust extractor doesn't consistently produce dust

### ISSUE THREAD

**Issue by Boomer-1** [Mooy1/InfinityExpansion#75]
## Description (Required)

power up a dust extractor and supply cobblestone to it. you will not always produce dust.

## Steps to reproduce the Issue (Required)

https://youtu.be/3bzD8fmoCyk

## Expected behavior (Required)

dust to be consistently produced

## Server Log / Error Report

no errors in server log

## Environment (Required)

 - Minecraft Version:1.17.1
 - Slimefun Version:966
 - Plugin Version: 121

**Comment by Mooy1** [comment]
Should be fixed with latest build, it worked fine in my test server but lmk if it still doesnt.

**Comment by Boomer-1** [comment]
ok
