### ISSUE TITLE
blockbreak glitch

### ISSUE THREAD

**Issue by zwrumpy** [Mooy1/InfinityExpansion#77]
## Description 
storage drops normal wood log

## Steps to reproduce the Issue
1. place a infinity storage > advance storage
2. break it 
3. drops 1 advance storage 1 normal wood log

## Expected behavior 
only drops 1 advance storage 

## Server Log / Error Report
no server log

## Environment (Required)
 - Minecraft Version: 1.17.1 
 - Slimefun Version: rc28
 - Plugin Version: dev121

**Comment by Mooy1** [comment]
should be fixed in build 123
