### ISSUE TITLE
Suggestion: infinity Geo quarry

### ISSUE THREAD

**Issue by xX-GATT-Xx** [Mooy1/InfinityExpansion#81]
The Geo quarry is a little slow to be worth the effort. maybe adding a faster version would increase incentives to make Geo quarries.

**Comment by Mooy1** [comment]
you can put a suggestion in the slimefun discord so people can vote for it, but the geo quarry is already considered a bit op since geo resources are supposed to be hard to get. I would probably accept a pr for it tho with a hard recipe.
