### ISSUE TITLE
Do not sync energy generation amount with Slimefun custom-ticker-delay

### ISSUE THREAD

**Issue by noiverre** [Mooy1/InfinityExpansion#83]
## Description (Required)
All of Infinity Expansion J/s energy generation will be synced with SlimeFun custom-ticker-delay: under URID: settings.

## Steps to reproduce the Issue (Required)
1. See /sf guide with default slimefun and infinity settings
2. Modify custom-ticker-delay in Slimefun settings
3. Restart the server
4. Check the energy generation result

## Expected behavior (Required)
Energy generation amount keeps the default values even with modified custom-ticker-delay

## Server Log / Error Report
-

## Environment (Required)
![image](https://user-images.githubusercontent.com/77881970/146453993-a8506db2-f7a0-4761-b906-b96d991d2849.png)

**Comment by Mooy1** [comment]
you have to restart the server between changing the value

**Comment by noiverre** [comment]
I'm aware that the server needs to be restarted. I forgot to write it up there.

However take a look at this example.
Using default SF settings, Infinity Reactor generates 240.000 J/s. Try lowering the custom-ticker-delay value in slimefun config, restart your server, and the Infinity Reactor will have its output lowered based on the value you input earlier.

![image](https://user-images.githubusercontent.com/77881970/146598595-f70a0838-cb8a-4792-b19c-637b662868cd.png)
![image](https://user-images.githubusercontent.com/77881970/146598614-9272ff1b-a300-4f4d-97f0-c48b61bd0c31.png)
![image](https://user-images.githubusercontent.com/77881970/146598624-33849f38-84f6-4a13-af7d-0c491fa217d4.png)

Their values should remain the same, no matter what value you input in the custom ticker. 240k J/s should remain at 240k J/s even if the custom ticker is set to 100 or anything

**Comment by noiverre** [comment]
Infinity Expansion is meant for end-game machines, so if a server uses high custom-ticker-delay value to help their performance, what is the point of doing Infinity if another add-ons or even the default SF generator can outperform Infinity energy generation?

**Comment by Mooy1** [comment]
that is how it is supposed to be, all addons and normal slimefun work this way. they just dont update the displayed values.
