### ISSUE TITLE
Storage units turns into vanilla woods on random occassion

### ISSUE THREAD

**Issue by noiverre** [Mooy1/InfinityExpansion#85]
## Description (Required)
Any Infinity Expansion storage units randomly turned into woods, I had several players reporting that their storage units got corrupted right after they opened and closed it. There are also several reports claiming the storage units broken occassionally along with its contents right after the server stopped in a safe way

## Steps to reproduce the Issue (Required)
Don't know. It happened randomly

## Expected behavior (Required)
Storage units keeps being storage units without turning into woods
This doesn't happen to any other add-ons

## Server Log / Error Report
None, though this could be related:
https://pastebin.com/0F13nx0j
https://pastebin.com/QNWbCuAG

## Environment (Required)
Java Environment:
  Operating System: Linux
  Java Version: 17.0.1
 
Server Software: Airplane
  Build: git-Airplane-110 (MC: 1.17.1)
  Minecraft v1.17.1-R0.1-SNAPSHOT
 
Slimefun Environment:
  Slimefun vDEV - 985 (git 1f3d0f5c)
  Caused by: InfinityExpansion vDEV - 124 (git 9f240edd)
 
Installed Addons (6)
  + EcoPower DEV - 5 (git 5c1ecd68)
  + LiteXpansion DEV - 160 (git 4ec7615b)
  + ExtraTools DEV - 31 (git abdc1514)
  + FoxyMachines DEV - 51 (git 3493db25)
  + FluffyMachines DEV - 94 (git c5a76c49)
  + InfinityExpansion DEV - 124 (git 9f240edd)

**Comment by noiverre** [comment]
Potentially the same issue as #79 but not sure

**Comment by Mooy1** [comment]
Could you post your startup logs, and make sure slimefuns log duplicate blocks option is enabled in the config.
