### ISSUE TITLE
Problems with the barrel plug and "lands"

### ISSUE THREAD

**Issue by ArrozElManko** [Mooy1/InfinityExpansion#90]
Hi, my players reported a problem with the "Infinityexpasion" addon and the "lands" plugin.

The problem is that a player x can steal things in the barrels in protected areas, the lands plugin from what I saw has support with slimefun, I will still be reporting any inconvenience

## Steps to reproduce the Issue (Required)
https://imgur.com/a/a7r1bBv

## Expected behavior (Required)
What you thought you can not, steal or interact with those barrels in protected area

## Server Log / Error Report
No error in console

## Environment (Required)
https://imgur.com/a/ZNI0ZOC

**Comment by Mooy1** [comment]
This would be an issue with slimefun, dough, or lands. i just use the slimefun/dough api
