### ISSUE TITLE
Soulbound on sky piercer (infinity bow) doesn't work

### ISSUE THREAD

**Issue by StefanMarinkov05** [Mooy1/InfinityExpansion#91]
# Description (Required)
When you die Sky piercer doesn't stay in your inventory when you respawn but other gears stays after you respawn

# Steps to reproduce the Issue (Required)
got INFINITY_BOW (and other inf. gears just to see the diferences) and die (doesn't matter how) and will see that all gears except the infinity bow stays in your inv when you respawn

# Expected behavior (Required)
All inf. gears to stay in my inventory when I respawn

# Server Log / Error Report
https://i.imgur.com/LCP1T0l.gif

# Possible fix (I'm not fully sure about that)
In https://github.com/Mooy1/InfinityExpansion/blob/master/src/main/java/io/github/mooy1/infinityexpansion/items/gear/InfinityBow.java change line 21 from "*public final class InfinityBow extends ExplosiveBow {*" to
"*public final class InfinityBow extends ExplosiveBow   implements Soulbound, NotPlaceable {*"
and add "*import io.github.thebusybiscuit.slimefun4.core.attributes.Soulbound;*" before it

# Environment (Required)
Minecraft Version: 1.18.1
Slimefun Version: DEV - 994 (git eac32ac9)
Plugin Version: DEV - 130 (git a2773c8)

**Comment by Mooy1** [comment]
Sorry for late response, fixed it
