### ISSUE TITLE
Update to 1.18

### ISSUE THREAD

**Issue by CleanCutBloons** [Mooy1/InfinityExpansion#93]
## Description (Required)
Infinity Expansion only works on 1.16.x and 1.17.x. It does not work on 1.18.x even though Slimefun works.

## Steps to reproduce the Issue (Required)
1. Go to InfinityExpansion Downloads
2. Click on 132
3. See Versions: 1.16.x, 1.17.x

## Expected behavior (Required)
The plugin would work on 1.18

## Server Log / Error Report
None

## Environment (Required)
 - Minecraft Version: 1.18.1
 - Slimefun Version: 999
 - Plugin Version: 132

**Comment by Mooy1** [comment]
it works fine
