### ISSUE TITLE
Incorrect Decompressor Recipes allow for Duping of Quartz & Cobblestone

### ISSUE THREAD

**Issue by BurningBrimstone** [Mooy1/InfinityExpansion#94]
## Steps to reproduce the Issue (Required)

Craft a Quartz block using 4 Nether Quartz; then use the Decompressor to decompress the block. Recipe result is 9 Nether Quartz.

Alternatively, use a cobble press to compress cobblestone. Costs 64 & Results in 8 Compressed. Decompress for 81 Cobblestone.

## Expected behavior (Required)

Nether quartz blocks should output 4 nether quartz, not 9. And compressed cobblestone should output 8 of the tier below, not 9.
## Environment (Required)

![image](https://user-images.githubusercontent.com/58698520/155066263-7cc17427-4c8c-438d-936e-c551c105e0cc.png)

**Comment by Boomer-1** [comment]
with 4 machines making compressed cobblestone, 3 require 9, 1 requires 8. not sure I'd agree that the decompressor should yield 8.
