### ISSUE TITLE
powered bedrock does not revert when unpowered and it cannot be mined up.

### ISSUE THREAD

**Issue by Boomer-1** [Mooy1/InfinityExpansion#99]
## Description (Required)

After powering the powered bedrock block, it turned into bedrock. After removing all power sources in the network, it stayed bedrock. I was not able to mine it up, and it never converted back to it's original state to mine. i had to remove it in creative, where it turned back into its original texture.

## Steps to reproduce the Issue (Required)

Place down powered bedrock
power it
remove power source

![2022-03-06_14 52 10](https://user-images.githubusercontent.com/75179680/156941811-e9d757ab-01e0-4207-bdba-686d080b905f.png)

## Expected behavior (Required)

block to revert to it's netherite texture and be mineable

## Server Log / Error Report

no errors

## Environment (Required)

 - Minecraft Version: 1.18.1
 - Slimefun Version: 999
 - Plugin Version: 135

**Comment by JiangQiYan713** [comment]
I hope the author can fix this bug as soon as possible, or delete it in subsequent versions. Using the wrench of the fluffy machine, I successfully dug out the bedrock body machine that can not restore the original power, but there is a chance to card out the bedrock that can not be destroyed by the survival mode players.
希望作者尽快修复这个bug，或者在后续的版本中删除他。我利用蓬松机器的扳手成功挖掉了无法恢复原样的动力基岩本体机器，但是有概率卡出真正无法被生存模式玩家破坏的基岩。

**Comment by JiangQiYan713** [comment]
https://user-images.githubusercontent.com/91627081/164121155-36652f45-270e-470f-9964-1faa493b1e28.mp4
